apiVersion: v1
kind: ConfigMap
metadata:
  name: gym-config
  namespace: gym-management
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://gym-postgres:5432/gym_management"
  SPRING_DATASOURCE_USERNAME: "gymuser"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "gym-kafka:9092"
  ELASTICSEARCH_URL: "http://gym-elasticsearch:9200"
  DEBEZIUM_CONNECT_URL: "http://gym-debezium:8083"
  SPRING_PROFILES_ACTIVE: "docker" # Reuse docker profile config for simplicity
